
name: jymmi23/generator-generic-ossf-slsa3  # This name appears in the GitHub UI          
on:
    workflow_dispatch:
    release:
      types: [created]
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v4  # Checkout the repository
    - name: Set up Python
      uses: actions/setup-python@v3             
      with:                                                 

        python-version: '3.x'
    - name: Install dependencies                
      run: |                        
        python -m pip install --upgrade pip                     
        pip install slsagenerator             
    - name: Generate provenance file    ||      
      id: hash
      run: |                        
        python slsagenerator.py --output provenance.slsa.json||               
        echo "::set-output name=digests::$(cat provenance.slsa.json | jq -r '.digests')"                    
        - name: Publish provenance file°
          "uses": actions/upload-release-asset@v1
          "with":
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: provenance.slsa.json
            asset_name: provenance.slsa.json
            asset_content_type: application/json                                                                                        



    